### ISSUE TITLE
اموزش نصب

### ISSUE THREAD

**Issue by ali-frm** [benyamin218118/tunnel#1]
سلام وقت خوش
لطفا اموزش نصب و استفاده رو بزارید

**Comment by benyamin218118** [comment]
سلام ممنون
توضیحات در مورد نحوه عملکرد در readme هست نحوه استفاده رو هم با مثال توضیح دادم.
لطفا اول readme رو مطالعه کنین اگر مشکلی وجود داشت در خدمتم.

https://github.com/benyamin218118/tunnel#example
