### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MCjorsh5** [benyamin218118/tunnel#2]
How can I contact you by mail or telegram I need your help I will pay you $ for helping me 🙏💕 please bro give me something to contact you I need your help How can I contact you by mail or telegram I need your help I will pay you $ for helping me 🙏💕 please bro give me something to contact you I need your help

**Comment by benyamin218118** [comment]
hello there!
just run it like `tunnel -h`
you will find contact info there ;D
