### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by MILADALEF** [benyamin218118/tunnel#3]
سلام . اگر در دستور روی سرور ایران بجای آیپی dest دامنه سرور خارج رو که پشت سی دی ان هست بذاریم باز هم تانل برقرار میشه ؟

**Comment by benyamin218118** [comment]
سلام ببخشین دیرجواب میدم ندیده بودم issue رو.
بله در توضیحات یه بخش مربوط به cdn داریم که همین رو توضیح میده

https://github.com/benyamin218118/tunnel#cdn
